config/urls.py
from django.urls import include, path, re_path
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.sitemaps.views import sitemap
from config.sitemaps import VideoSitemap
from config.views import *

sitemaps = {
    'videos': VideoSitemap,
}


urlpatterns = [
    re_path(r'^sitemap\.xml$', sitemap, {
            'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    re_path(r'^sitemap-(?P<section>.+)\.xml$', sitemap, {'sitemaps': sitemaps},
            name='django.contrib.sitemaps.views.sitemap'),
    re_path(r'^e1da49db34b0bdfdddaba2ad6552f848/$', sitemap, {'sitemaps': sitemaps},
            name='django.contrib.sitemaps.views.sitemap'),
    re_path(r'^robots\.txt', include('robots.urls')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^about/$', AboutPage.as_view(), name="about-page"),
    re_path(r'^login/$', LoginView.as_view(), name='login'),
    re_path(r'^logout/$', LogoutView.as_view(),
            {'next_page': '/'}, name='logout'),
    re_path(r'^captcha/', include('captcha.urls')),
    re_path(r'', include('videos.urls')),
    re_path(r'', include('feedback.urls')),
]
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feedback/urls.py
from django.urls import re_path
from .views import FeedbackPage
app_name = 'feedback'
urlpatterns = [
    re_path(r'^feedback$', FeedbackPage.as_view(), name="feedback-page"),
]

videos/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from .views import *

app_name = "videos"
router = routers.SimpleRouter()
router.register(r'api/videos/admin', EditorVideoViewSet, basename="videos")
router.register(r'api/videos', VideoViewSet, basename="videos-readonly")
# router.register(r'accounts', AccountViewSet)

urlpatterns = [
    # url("api/", include([
    #     url("bodycams", BodycamsAPI.as_view(), name="api-bodycams"),
    # ])),
    url(r'^$', VideoIndexView.as_view(), name="index"),
    # url(r'^/dashboard$', VideoDashboard.as_view(), name="dashboard"),
    # url(r'^/dashboard/(?P<date>[0-9]+)$',
    #     VideoDashboard.as_view(), name="dashboard-date"),
    # url(r'^ajax/', include([
    #     url(r'^bodycams/json$', BodycamData.as_view(), name="bodycam-data"),
    #     url(r'^bodycam/submit$', BodycamSubmit.as_view(), name="bodycam-submit"),
    #     url(r'^bodycam/edit$', BodycamEdit.as_view(), name="bodycam-edit"),
    #     url(r'^bodycam/link$', BodycamLink.as_view(), name="link-bodycam-shooting"),
    # ]))
] + router.urls

config/views.py
from django.shortcuts import render
from django.views import View


class AboutPage(View):
    def get(self, request):
        return render(request, "config/about.html", {})

config/templates/partials/globals.html
<script type="text/javascript">
  const ALL_TAGS = [
      {% for tag in all_tags %}
      {
          id: {{tag.id}},
          value: `{{tag.text}}`,
          display: `{{tag.text}}`
      },
      {% endfor %}
  ];
  const STATES = [
      {% for state in states %}
      {
          value: `{{state.0}}`,
          display: `{{state.1}}`
      },
      {% endfor %}
  ]
  {% if user.is_authenticated %}
    var URLS = {
    }
    var CSRFMIDDLEWARETOKEN = "{{csrf_token}}";
  {% endif %}
</script>

config/templates/partials/head.html
{% load static %}
<meta charset="utf-8" />
<meta name="google-site-verification" content="S97wnMfRrGrCTgw1oK0OThteMbwPbAo7iOhrmDmta_8" />
<meta name="description" content="An interactive list of police videos for {{title_current_year}}." />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<meta http-equiv="x-ua-compatible" content="ie=edge" />

<link rel="stylesheet" href="https://unpkg.com/vue-multiselect@2.1.0/dist/vue-multiselect.min.css" />
<!-- CSS only -->
<link
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
  rel="stylesheet"
  integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
  crossorigin="anonymous"
/>

<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
  integrity="sha512-SfTiTlX6kk+qitfevl/7LibUOeJWlt9rbyDn92a1DqWOw9vWG2MFoays0sgObmWazO5BQPiFucnnEAjpAB+/Sw=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
/>

<link rel="shortcut icon" type="image/png" href="{% static 'css/new_favicon.ico' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}" />
<!-- dynamic follows -->

config/templates/partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'videos:index' %}">
            Officer Involved
            <svg enable-background="new 0 0 24 24" viewBox="0 0 24 24">
                <path d="M20,14.5c0,0-2.3,5.5-8,5.5s-8-5.5-8-5.5s4.1,1,7.9,1S20,14.5,20,14.5z"/>
                <path d="M21.3,8.5C17.1,7.2,13.8,4,12,4c-1.8,0-5.1,3.2-9.3,4.5c-0.7,0.2-1,1-0.6,1.6C3,11.3,4,11.4,4,12.8c0,0,4,1,8,1s8-1,8-1  c0-1.4,1-1.5,1.8-2.8C22.2,9.5,21.9,8.7,21.3,8.5z M12,12c-1.1,0-2-1.9-2-3c0,0,0.9-1,2-1s2,1,2,1C14,10.1,13.1,12,12,12z"/>
            </svg>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
            <a class="nav-link" href="{% url 'about-page' %}">About</a>
            </li>
        </ul>
        <ul class="navbar-nav me-auto flex-grow-1 justify-content-end">
            {% if not user.is_authenticated %}
                <li class="nav-item">
                <a class="nav-link" href="{% url 'feedback:feedback-page' %}">
                    Give Feedback
                </a>
            </li>
            {% endif %}
            {% if user.is_staff %}
            <li class="nav-item">
                <a class="nav-link" href="/admin">{{number_of_feedbacks}} Feedback</a>
            </li>
            {% endif %}
            {% if user.is_superuser %}
            
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Admin Actions
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    
                    <li>
                        <button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#videoModal">Submit New Video</button>
                    </li>
                </ul>
              </li>
            </li>
            {% endif %}
            {% if user.is_authenticated %}
                <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Sign Out <i class="fa fa-sign-out" aria-hidden="true"></i></a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Sign In <i class="fa fa-sign-in" aria-hidden="true"></i></a>
            </li>
            {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% if user.is_authenticated %}
{% include 'partials/modal.html' %}
{% endif %}

config/templates/partials/scripts.html
{% load static %}
<!-- <script src="https://cdn.jsdelivr.net/npm/vue@2.6.14"></script> -->
<script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.auto.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.js"></script>
<script src="https://unpkg.com/vuex@3.6.2/dist/vuex.js"></script>
<script src="https://unpkg.com/vue-multiselect@2.1.0"></script>
<script src="https://cdn.jsdelivr.net/npm/vue-pagination-2@3.0.91/dist/vue-pagination-2.min.js"></script>
<script src="https://unpkg.com/vue-toasted"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js" integrity="sha512-bZS47S7sPOxkjU/4Bt0zrhEtWx0y0CRkhEp8IckzK+ltifIIE9EMIMTuT/mEzoIMewUINruDBIR/jJnbguonqQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<!-- JavaScript Bundle with Popper -->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js" integrity="sha512-qTXRIMyZIFb8iQcfjXWCO8+M5Tbc38Qi5WzdPOYZHIlZpzBHG3L3by84BBBOiRGiEb7KKtAOAs5qYdUiZiQNNQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>


<!-- javascript will go here -->
<script type="text/javascript">
    Vue.config.productionTip = false
    // Test browser
    navigator.browserSpecs = (function(){
        var ua = navigator.userAgent, tem, 
            M = ua.match(/(opera|chrome|safari|firefox|msie|trident(?=\/))\/?\s*(\d+)/i) || [];
        if(/trident/i.test(M[1])){
            tem = /\brv[ :]+(\d+)/g.exec(ua) || [];
            return {name:'IE',version:(tem[1] || '')};
        }
        if(M[1]=== 'Chrome'){
            tem = ua.match(/\b(OPR|Edge)\/(\d+)/);
            if(tem != null) return {name:tem[1].replace('OPR', 'Opera'),version:tem[2]};
        }
        M = M[2]? [M[1], M[2]]: [navigator.appName, navigator.appVersion, '-?'];
        if((tem = ua.match(/version\/(\d+)/i))!= null)
            M.splice(1, 1, tem[1]);
        return {name:M[0], version:M[1]};
    })();
    function alertBrowser(browser_name, version) {
        content = "We've detected you're using " + browser_name + " version " + version + " which is incompatible with this website.<br><br> Please consider upgrading to the newest version of Microsoft Edge, Chrome, Firefox or Opera, as the website will not function on your current browser. <br><br> We've provided links below.<br><br> <a href='https://www.microsoft.com/en-us/windows/microsoft-edge?irgwc=1&OCID=AID681541_aff_7593_1239139&tduid=(ir__kdxqv1ge09u2oa0jv166ambmqm2xk9tn6hzo3fct00)(7593)(1239139)(DLButton)(microsoftedge)&irclickid=_kdxqv1ge09u2oa0jv166ambmqm2xk9tn6hzo3fct00'>Edge Update</a><br><a href='https://www.google.com/chrome/'>Chrome Update</a><br><a href='https://www.mozilla.org/en-US/firefox/'>Firefox Update</a><br><a href='https://www.opera.com/'>Opera Update</a>"
          $.alert({
            title: 'Browser Version Issue!',
            content: content,
            type: 'orange',
            typeAnimated: true,
            autoClose: '',
            buttons: {
            }
        });
    }
    if (navigator.browserSpecs.name == 'IE') {
        alertBrowser("Internet Explorer", navigator.browserSpecs.version)
    }
    else if (navigator.browserSpecs.name == "Firefox") {
        // Do something for Firefox.
        if (navigator.browserSpecs.version < 27) {
            alertBrowser("Firefox", navigator.browserSpecs.version)
        }
    }
    else if (navigator.browserSpecs.name == "Chrome") {
        if (navigator.browserSpecs.version < 29) {
            alertBrowser("Chrome", navigator.browserSpecs.version)
        }
    }
    else if (navigator.browserSpecs.name == "Safari") {
        if (navigator.browserSpecs.version < 9) {
            alertBrowser("Safari", navigator.browserSpecs.version)
        }
    }
    else if (navigator.browserSpecs.name == "Opera") {
        if (navigator.browserSpecs.version < 17) {
            alertBrowser("Opera", navigator.browserSpecs.version)
        }
    }

</script>

config/templates/partials/timeline.html
<div class="row">
    <div class="col-lg-12 justify-items-center">
        <div class="timeline">
            <a 
                v-if="year != 2013"
                v-bind:href="calculatePreviousYear()"
                class="fa fa-chevron-left timeline-arrow"
                id="timeline-arrow-left"
                aria-label="Previous Year">
            </a>
            <div class="timeline-container">
                <ul id="dates">
                    {% for for_year in valid_years %}
                        <li id="timelineYear{{for_year}}"><a class="{% if for_year == year %}timeline-selected-year{% endif %}"href="{% url 'videos:date-index' date=for_year %}">{{for_year}}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <a 
                v-if="year != currentYear"
                v-bind:href="calculateNextYear()"
                class="fa fa-chevron-right timeline-arrow"
                id="timeline-arrow-right"
                aria-label="Next Year">
            </a>
          </div>
    </div>
</div>